version: "3.9"
services:
  web:
    build: .
    depends_on:
      - db
      - redis
      - processor
    restart: always
    volumes:
      - .:/home/badamczyk/webtetrado
      - ./static:/home/badamczyk/webtetrado/static
      - ./media:/home/badamczyk/webtetrado/media
    entrypoint: bash ./docker-entrypoint.sh
    networks:
      - web_network
      - db_network
      - redis_network
      - processor_network
    links:
      - redis
      - processor
      
  processor:
    image: webtetrado
    environment:
      - WORKDIR=/mnt/workdir
      - QBASE_JAR=/qbase-backend.jar
      - LOGLEVEL=INFO
    volumes:
      - workdir:/mnt/workdir
    networks:
      - processor_network

  nginx:
      build:
        context: ./nginx
      ports:
        - 80:8080
        - 443:443
      depends_on:
        - web
      volumes:
        - ./static:/home/badamczyk/webtetrado/static
        - ./media:/home/badamczyk/webtetrado/media
        - ./ssl:/etc/letsencrypt/
        - ./nginx/conf/:/etc/nginx/conf.d/
      networks:
        - web_network
      expose:
        - "80"
      
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./db_env.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - db_network

  redis:
    image: redis:alpine
    restart: always
    networks:
      - redis_network

volumes:
  workdir:
  pgdata:

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge
  redis_network:
    driver: bridge
  processor_network:
    driver: bridge
