version: "3.9"
services:
  web:
    build: .
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - .:/opt/webtetrado
    entrypoint: bash ./docker-entrypoint.sh
    networks:
      - web_network
      - db_network
      - redis_network
    environment:
      - DEBUG=False
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    links:
      - redis
      
  nginx:
      build:
        context: ./nginx
      ports:
        - 80:8080
        - 443:443
      depends_on:
        - web
      volumes:
        - ./static:/opt/webtetrado/static
        - ./media:/opt/webtetrado/media
        - ./ssl:/etc/letsencrypt/
        - ./nginx/conf/:/etc/nginx/conf.d/
        - ./logs/nginx:/logs
      networks:
        - web_network
      expose:
        - "80"
      
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - db_network

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis_network

volumes:
  workdir:
  pgdata:

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge
  redis_network:
    driver: bridge
