version: "3.9"
services:
  web:
    build: .
    depends_on:
      - db
      - redis
      - webtetrado_backend
    restart: always
    volumes:
      - ./static:/opt/webtetrado/static
      - ./media:/opt/webtetrado/media
      - ./logs:/logs
        #    - .:/opt/webtetrado
    entrypoint: sh ./docker-entrypoint.sh
    networks:
      - web_network
      - db_network
      - redis_network
      - webtetrado_backend_network
    environment:
      - DEBUG = False
    links:
      - redis
      - webtetrado_backend
      
  webtetrado_backend:
    image: webtetrado
    restart: always
    environment:
      - WORKDIR=/mnt/workdir
      - QBASE_JAR=/qbase-backend.jar
      - LOGLEVEL=INFO
    volumes:
      - workdir:/mnt/workdir
    networks:
      - webtetrado_backend_network

  nginx:
      build:
        context: ./nginx
      restart: always
      ports:
        - 8080:8080
      depends_on:
        - web
      volumes:
        - ./static:/opt/webtetrado/static
        - ./media:/opt/webtetrado/media
        - ./nginx/conf/:/etc/nginx/conf.d/
        - ./logs/nginx:/logs
      networks:
        - web_network
      
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - db_network

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis_network

volumes:
  workdir:
  pgdata:

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge
  redis_network:
    driver: bridge
  webtetrado_backend_network:
    driver: bridge
