# Generated by Django 4.0.2 on 2022-02-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryfile',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
