export const SecondaryStructureDrawingHelpSection = () => {
  return (
    <div>
      <h3 id={"secondary_drawing_varna"}>
        3.1.{" "}
        <a href="https://academic.oup.com/bioinformatics/article/25/15/1974/210730">
          VARNA (Visualization Applet for RNA)
        </a>
      </h3>
      <p>
        VARNA is mainly an interactive software for drawing and editing RNA
        secondary structures. It supports several input file formats, including
        BPSEQ, CT and others. The main advantage of VARNA is its support for
        non-canonical base pairs (
        <a href="http://rnajournal.cshlp.org/content/7/4/499.long">
          Leontis/Westhof
        </a>
        &nbsp; nomenclature) and pseudoknots (first extracted maximal planar
        subset of canonical base pairs is a scaffold for the rest of the base
        pairings). The output visualisation can be extracted in vector and
        bitmap picture formats including EPS, SVG, XFIG, JPG, or PNG. VARNA is
        available as the lightweight applet and swing component at{" "}
        <a href="http://varna.lri.fr/">http://varna.lri.fr/</a>.
      </p>
      <h3 id={"secondary_drawing_rchie"}>
        3.2.{" "}
        <a href="https://academic.oup.com/nar/article/40/12/e95/2414962">
          R-chie
        </a>
      </h3>
      <p>
        R-chie is a tool for generating different types of arc diagrams. It
        supports visualization of multiple sequence alignments and incorporation
        of co-variance information into the image. R-chie can read inputs in
        various formats including BPSEQ, CT and dot-bracket, also these
        containing higher order pseudoknots. It is highly configurable and
        allows to save output as PNG or PDF files. The webserver is available at{" "}
        <a href="http://www.e-rna.org/r-chie">http://www.e-rna.org/r-chie</a>.
      </p>
      <h3 id={"secondary_drawing_pseudoknot"}>
        3.3. Pseudoknot annotation scripts
      </h3>
      <p>
        Graphical images of RNA secondary structure generated by PseudoViewer
        and VARNA are post-processed by the RNApdbee scripts. Their aim is to
        annotate the orders of pseudoknot interactions in a graphical way.
        Different colours have been assigned to particular pseudoknot orders:
      </p>
      <table id={"pseudoknot-table"}>
        <tbody>
          <tr>
            <td>
              <b>Pseudoknot order</b>
            </td>
            <td>1st</td>
            <td>2nd</td>
            <td>3rd</td>
            <td>4th</td>
            <td>5th</td>
            <td>6th</td>
            <td>7th</td>
            <td>8th</td>
          </tr>
          <tr>
            <td>
              <b>Text annotation (brackets &amp; letter)</b>
            </td>
            <td>[]</td>
            <td>{"{}"}</td>
            <td>&lt;&gt;</td>
            <td>Aa</td>
            <td>Bb</td>
            <td>Cc</td>
            <td>Dd</td>
            <td>Ee</td>
          </tr>
          <tr>
            <td>
              <b>Graphical annotation (colours)</b>
            </td>
            <td style={{ backgroundColor: "rgb(0, 114, 0)" }}></td>
            <td style={{ backgroundColor: "rgb(5, 32, 96)" }}></td>
            <td style={{ backgroundColor: "rgb(143, 0, 0)" }}></td>
            <td style={{ backgroundColor: "rgb(93, 0, 93)" }}></td>
            <td style={{ backgroundColor: "rgb(60, 115, 157)" }}></td>
            <td style={{ backgroundColor: "rgb(143, 118, 0)" }}></td>
            <td style={{ backgroundColor: "rgb(218, 95, 210)" }}></td>
            <td style={{ backgroundColor: "rgb(159, 185, 37)" }}></td>
          </tr>
        </tbody>
      </table>
      <br />
      <h3 id={"secondary_drawing_interactions"}>
        3.4. Scripts to annotate non-canonical interactions
      </h3>
      <p>
        Additional scripts post-process the VARNA and PseudoViewer images to
        display non-canonical interactions. VARNA visualization supports
        Leontis/Westhof classification and it is used during RNApdbee
        post-processing (see table below). In case of PseudoViewer, the
        non-canonical interactions are shown either as gray-filled circles (for
        regular bps) or coloured dashed lines (for pseudoknots, see table of
        colours above). Gray dashed lines are used to connect multiplet-involved
        residues and other pairs unrepresentable in text format.
      </p>
      <table id={"visualization-symbol-table"}>
        <tbody>
          <tr>
            <td>
              <b>RNA base-base classification</b>
            </td>
            <td>
              <b>Visualization symbol</b>
            </td>
          </tr>
          <tr>
            <td>cis Watson-Crick Watson-Crick</td>
            <td>
              <img
                alt={"symbol-cww"}
                src={require("../../assets/varna-symbol/symbol-cww.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>trans Watson-Crick Watson-Crick</td>
            <td>
              <img
                alt={"symbol-tww"}
                src={require("../../assets/varna-symbol/symbol-tww.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>cis Watson-Crick Hoogsteen</td>
            <td>
              <img
                alt={"symbol-cwh"}
                src={require("../../assets/varna-symbol/symbol-cwh.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>trans Watson-Crick Hoogsteen</td>
            <td>
              <img
                alt={"symbol-twh"}
                src={require("../../assets/varna-symbol/symbol-twh.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>cis Watson-Crick Sugar</td>
            <td>
              <img
                alt={"symbol-cws"}
                src={require("../../assets/varna-symbol/symbol-cws.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>trans Watson-Crick Sugar</td>
            <td>
              <img
                alt={"symbol-tws"}
                src={require("../../assets/varna-symbol/symbol-tws.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>cis Hoogsteen Watson-Crick</td>
            <td>
              <img
                alt={"symbol-chw"}
                src={require("../../assets/varna-symbol/symbol-chw.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>trans Hoogsteen Watson-Crick</td>
            <td>
              <img
                alt={"symbol-thw"}
                src={require("../../assets/varna-symbol/symbol-thw.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>cis Hoogsteen Hoogsteen</td>
            <td>
              <img
                alt={"symbol-chh"}
                src={require("../../assets/varna-symbol/symbol-chh.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>trans Hoogsteen Hoogsteen</td>
            <td>
              <img
                alt={"symbol-thh"}
                src={require("../../assets/varna-symbol/symbol-thh.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>cis Hoogsteen Sugar</td>
            <td>
              <img
                alt={"symbol-chs"}
                src={require("../../assets/varna-symbol/symbol-chs.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>trans Hoogsteen Sugar</td>
            <td>
              <img
                alt={"symbol-ths"}
                src={require("../../assets/varna-symbol/symbol-ths.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>cis Sugar Watson-Crick</td>
            <td>
              <img
                alt={"symbol-csw"}
                src={require("../../assets/varna-symbol/symbol-csw.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>trans Sugar Watson-Crick</td>
            <td>
              <img
                alt={"symbol-tsw"}
                src={require("../../assets/varna-symbol/symbol-tsw.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>cis Sugar Hoogsteen</td>
            <td>
              <img
                alt={"symbol-csh"}
                src={require("../../assets/varna-symbol/symbol-csh.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>trans Sugar Hoogsteen</td>
            <td>
              <img
                alt={"symbol-tsh"}
                src={require("../../assets/varna-symbol/symbol-tsh.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>cis Sugar Sugar</td>
            <td>
              <img
                alt={"symbol-css"}
                src={require("../../assets/varna-symbol/symbol-css.svg")}
              />
            </td>
          </tr>
          <tr>
            <td>trans Sugar Sugar</td>
            <td>
              <img
                alt={"symbol-tss"}
                src={require("../../assets/varna-symbol/symbol-tss.svg")}
              />
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
};
